version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17	
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build --configuration production
      - docker build -t 205555772354.dkr.ecr.us-east-1.amazonaws.com/angular-repo:latest .
      - docker tag angular-repo:latest 205555772354.dkr.ecr.us-east-1.amazonaws.com/angular-repo:latest .
  post_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username priyavj07 --password-Pr0jectsuid@12 205555772354.dkr.ecr.us-east-1.amazonaws.com
      - docker push 205555772354.dkr.ecr.us-east-1.amazonaws.com/angular-repo:latest .
artifacts:
  files:
    - dist/my-angular-project/**/*    # Adjust paths to match your directory structure
    - appspec.yml
    - deploy-scripts/**/*

